---
abstract: 'Extensible system to provide bash completion'
author:
  - 'Pedro Melo <melo@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101610'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bash-Completion
requires:
  File::Spec: 0
  Getopt::Long: 0
  Module::Pluggable: 0
resources:
  repository: http://github.com/melo/bash-completion.git
version: 0.001
